### ISSUE TITLE
Fleshing out CLI flags

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/systrace#12]
Here is a list of CLI flags we could add.  Please edit this description to add more, or check them off.

- [ ] `--tool libfoo.so`: allow the user to override the tool.  I suggest examples `echo.so` (systrace) and maybe `count.so` be included with this systrace repo.
- [x] `--env-all` pass through all env vars from the env, default "no".
- [x] `--env`: like the Docker option.  Note this supports both `--env X=3` and `--env X` (inherit from environment).

What else?

**Comment by wangbj** [comment]
* Added `--tool` command line option to specify tool explicitly;
* killed `--env-all`, now systrace inherits all environment variables from the tracer, unless specified with `--no-host-envs`.

**Comment by wangbj** [comment]
commit: cb36976302f7485fef1cc84a2a332d195c9b9cde
