### ISSUE TITLE
Rename/remove references to libdet & detsched

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/systrace#14]
Since systrace doesn't "know" what instrumentation purposes it is being put to, it shouldn't reference any higher-level components or naming conventions.  Close this issue when `git grep` doesn't have any mentions of those.

(This includes removing the `--detsched` flag of course.)

This is related to the little rename request mentioned at the end of https://github.com/iu-parfunc/systrace/issues/8.  (I.e. to remove `./libdet` and instead include `examples/echo` and `examples/count`).

**Comment by wangbj** [comment]
fixed in commit 119f2f628e89b3c409d2f25d35b519f0c9577883
