### ISSUE TITLE
Make namespace creation optional (default off)

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/systrace#15]
Right now systrace creates a new namespace, so that app PIDs always start at the same place.  Let's turn this off by default and hide it behind a flag.  It may be good in some cases, but not when:

 * a front-end "det" command is handling namespacing
 * namespaces prove insufficient to determinize PID, because of intra-container parallelism (later)

**Comment by wangbj** [comment]
fixed in 4cebe4fea19d8ad93880d0b11355debc6368b4b1
