### ISSUE TITLE
Remove environment masking and --env options

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/systrace#16]
As a follow-up to #15, masking the environment should really not be the job of systrace, because it can easily be done by some tool in front of systraces that calls it.  Masking the environment seems orthogonal to the core job of capturing syscalls/instructions and redirecting them.

**Comment by wangbj** [comment]
do you think the `envs` arguments should be completely gotten rid of? I changed the command lines options to allow passing through host's envs by default, see b96243f .

**Comment by wangbj** [comment]
Host envs are now passed into tracee unless `--no-host-envs` is specified.
