### ISSUE TITLE
--library-path shouldn't assume libtrampoline.so and libTOOL.so are in same dir!

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/systrace#31]
This expands on the topic of #29.  To reproduce this bug (as of commit e0b8156bdff6336):

```bash
$ cd systrace
$ make
$ mkdir ./mytool
$ mv lib/libecho.so mytool/
$ ./bin/systrace --library-path ./mytool/ --tool libecho.so /bin/ls
thread 'main' panicked at 'unable to load libtrampoline.so: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
```

That is because the current CLI conflates two things:

  * Where to find internal pieces of systrace itself (libtrampoline.so, in the future the dynamic loader too, right?)
  * Where to find the clients own tool.

I think these are only the same if you're a developer of systrace!  If systrace became popular and, e.g. got packaged for `apt-get install`, presumably you'd have `/usr/bin/systrace` and then `libtrampoline.so` in some standard system location.  Which implies:

 * [x] libtrampoline.so should be renamed something more unique, like `libsystrace-trampoline.so`.
 * [x] the ability to specify a directory like `--library-path` should be distinct for "internal bits" like trampoline.so vs the client instrumentation tools.

However, I'll revisit the point in #29.  I think that since there is only *one* libTOOL.so, having a search path for it is silly.  It's easier to just specify the file directly by its path.  So one solution here is for `--tool` to take a path and `--library-path` to be renamed and be only for internal bits.

**Comment by wangbj** [comment]
If we install `libsystrace-trampoline.so` into standard system location, then we probably don't need `--library-path` either, because we can search it from system library path, or use `LD_LIBRARY_PATH` environment variables if `libsystrace-trampoline.so` is not installed (yet).

**Comment by wangbj** [comment]
Also, do you think it is a good idea to build `libsystrace-trampoline.so` and `libTOOL.so` into a single shared library?

**Comment by wangbj** [comment]
change pushed in 7da571a.

* `--library-path` is used to search `libsystrace-trampoline.so` only
* `--tool` should also specify path

i.e.:

  ./systrace --library-path=target/debug --tool=target/debug/libecho.so <something>
